### ISSUE TITLE
Squiz problem

### ISSUE THREAD

**Issue by victoriafraser** [kentcc/kelsi#11]
this message happened when i just tried to upload a document to Squiz

504 Gateway Time-out
nginx

**Comment by LidorLapid** [comment]
Squiz does time out sometimes -- the hosting has been a bit flakey recently. Could you try uploading the document again please and let me know if you still experience this issue?

**Comment by LidorLapid** [comment]
I'll mark this as resolved for the time being. If you continue to experience this issue, please let me know.
