### ISSUE TITLE
text appearing strangely

### ISSUE THREAD

**Issue by victoriafraser** [kentcc/kelsi#12]
text is appearing strangely (not uniform) in preview at 

http://beta.kelsi.org.uk/inclusion-and-special-education-needs/early-help-and-preventative-services/kent-family-support-framework

It seems ok up to 
It has three interacting early help and prevention service delivery areas and processes:
Then it become faint and illegible fro the first bullet point onwards

**Comment by LidorLapid** [comment]
This is a content issue -- the text that doesn't appear correctly is inside a <div> instead of a <p>.

**Comment by charlottesales** [comment]
Have spoken to Victoria about how to amend this and what to do if it happens in the future.
