### ISSUE TITLE
Event listing - indenting

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#16]
In event assets, should the description text  be aligned slightly further right so it matches up with the start of the event name and the event month?

![image](https://cloud.githubusercontent.com/assets/10434416/5755604/7aaed42c-9c9e-11e4-9f54-7fbe769b7e78.png)

**Comment by LidorLapid** [comment]
Allan, can I have your input on this please? It might be worth considering restyling the date, as the current styling doesn't look right when an event's title spans more than one line (which will inevitably be the case).

**Comment by LidorLapid** [comment]
I've restyled the sidebar events listing based on discussions with Allan -- hopefully it looks better and makes more sense now! Let me know if any further changes are needed.
