### ISSUE TITLE
Event - location

### ISSUE THREAD

**Issue by missiles-82** [kentcc/kelsi#17]
Is there any chance of using the Description on the Details screen to populate the event details on the homepage (and other pages)? Currently publishers creating events have to write most of the details in the Details screen then write an additional description in the Metadata. This means the two descriptions (one in Metadata and one in Details) are different, which might be confusing. Did we decide against using ... where text reached its character limit on certain pages?

**Comment by LidorLapid** [comment]
My issue with pulling the data from the Description field on the Details screen is that this data is unclean -- i.e. it can have unwanted markup in it. I can strip out this markup, but this can result odd spacing where markup has been removed. For example, if you write the following text:

"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.

tempor incididunt ut labore et dolore magna aliqua."

It would look like this once the markup has been stripped off:

"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.tempor incididunt ut labore et dolore magna aliqua."

Note in particular the lack of space after the period.

Although I understand that from an editor's perspective, it would be easier to keep the editing to one screen, It would be risky for us to allow it to operate this way. I'm happy to change this if you're keen for me to do so, but my advice would be to keep it the way it is -- it would allow content editors finer control over the content that goes in there, and the end result will look much better.

**Comment by missiles-82** [comment]
Hi

Ok that’s good to know. As you say, let’s keep it this way and see what feedback we get from Victoria. I think I just found it odd I was entering the same info (potentially) in two places but perhaps it’s just me!

Ta

Cat

Catherine Iles | Digital Services | Kent County Council | External: 03000 416292 | Internal: 416292 | www.kent.gov.uk<http://www.kent.gov.uk/> | @kent_cc<http://www.twitter.com/kent_cc>
