### ISSUE TITLE
font in chrome

### ISSUE THREAD

**Issue by charlottesales** [kentcc/kelsi#18]
The font in chrome is slightly paler and thinner compared to the font in firefox. Not sure if this is an issue as also slightly happens on kent.gov but maybe something to look at. 

Thanks

**Comment by LidorLapid** [comment]
I've had a look in the latest versions of Firefox and Chrome and couldn't see a major difference in the way the font is rendered. Please could you let me know which versions of Chrome/Firefox you used, and also chuck a screenshot my way?

**Comment by charlottesales** [comment]
Hi Lidor,

Here are the screen shots:

For Firefox:


[cid:image001.jpg@01D033D5.6B2C9980]


For Chrome:


[cid:image002.jpg@01D033D5.6B2C9980]



Kind Regards

Charlotte

Charlotte Sales | Digital Services Project Officer | Kent County Council | Internal: 7200 416639 | External: 03000 416639 | www.kent.gov.uk<http://www.kent.gov.uk/> | [Follow Kent_cc on Twitter] @kent_cc<http://www.twitter.com/kent_cc>

**Comment by LidorLapid** [comment]
Thanks, Charlotte, but for some reason I can't see your screenshots. Not to worry, though. I'll have a look on my Windows machine -- it's likely just due to differences in how different browsers render fonts on different OSes.

**Comment by charlottesales** [comment]
Ok, let me know if not and I can show you on my screen.

Kind Regards

Charlotte

Charlotte Sales | Digital Services Project Officer | Kent County Council | Internal: 7200 416639 | External: 03000 416639 | www.kent.gov.uk<http://www.kent.gov.uk/> | [Follow Kent_cc on Twitter] @kent_cc<http://www.twitter.com/kent_cc>

**Comment by CatherineIles** [comment]
Yep it's faint on mine too, to the point where it's difficult to read, particularly links on standard content pages. Just adding my two pence :)

**Comment by LidorLapid** [comment]
Default font weight increased to 400 (up from 300).
