### ISSUE TITLE
2 page titles are appearing in preview

### ISSUE THREAD

**Issue by victoriafraser** [kentcc/kelsi#29]
![image](https://cloud.githubusercontent.com/assets/10435951/5853204/f5dbae52-a218-11e4-9873-b809264977bb.png)

**Comment by LidorLapid** [comment]
The H1 now gets pulled in automatically as part of the template, so you no longer have to manually insert it into your content. If you remove it from the content, only the blue H1 will remain on the page, as intended. Thanks!
