### ISSUE TITLE
Heading weirdness

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#38]
A very vague heading but not sure what else to call it! The headings of pages on my screen are showing odd pixels. See screen grab.

Thanks

![image](https://cloud.githubusercontent.com/assets/10434416/5916843/a5118a20-a60d-11e4-890a-bec25545ef31.png)

**Comment by LidorLapid** [comment]
Resolved. :) It was just a stray underline, but it did result in a rather "interesting" effect.
