### ISSUE TITLE
ebulletin archive page

### ISSUE THREAD

**Issue by charlottesales** [kentcc/kelsi#41]
Hi, 

I've created an e-bulletin archive page, which has some code from mailchimp on the edit contents screen, which then automatically pulls through the last copies of the ebulletin that has been mailed out. 

The font is just mailchimp arial at the moment though, so this might need looking at and changing to match the rest of the site. 
http://www.kent.gov.uk/_kelsi-beta/news-and-events/e-bulletin-archive/_nocache 

Thanks

**Comment by LidorLapid** [comment]
I've removed the unwanted styling -- this should be looking better now.
