### ISSUE TITLE
Print CSS

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#54]
Just tried printing a page and the text was overlapped (it was http://beta.kelsi.org.uk/support-for-children-and-young-people/kent-parenting-service) I haven't tried printing any thing else so far but could you review the print CSS please?

**Comment by LidorLapid** [comment]
Potentially due to the cookie banner -- will hide in print stylesheet.

**Comment by LidorLapid** [comment]
Corrected.
