### ISSUE TITLE
Sharing function on news

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#55]
Can I just check we're ok to use the social media sharing buttons on each Kelsi news item? And is there any customisation we can do on the message people receive (see below)? I'm guessing not!

http://beta.kelsi.org.uk/news-and-events/news/primary/business-rates-notifications#.VPWsX5TGNso.email
--- This message was sent by missiles_82@hotmail.com via http://addthis.com. Please note that AddThis does not verify email addresses.
Make sharing easier with the AddThis Toolbar: http://www.addthis.com/go/toolbar-em
To stop receiving any emails from AddThis, please visit: http://www.addthis.com/privacy/email-opt-out?e=.yNFT3JGY1xvQGMAb0JjXUZFY0ByAGFBcABzRQ

**Comment by LidorLapid** [comment]
Social media sharing buttons should be all OK to use. I haven't had the chance to test them, but they're ready-made ones provided by addthis.com so should work.

I certainly can change the email template -- what wording would you like on it?

**Comment by LidorLapid** [comment]
I've made some changes to the wording, so hopefully it should look a bit neater now. The only thing I can't change or get rid of is the last line,'To stop receiving...'. If we need more customisability I can build something from scratch for phase 2. Let me know if any other changes are needed to the wording in the meanwhile.
