### ISSUE TITLE
Primary setting news feed

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#57]
Hi. There are news items in the Primary news folder but they don't appear to be pulling through to the Primary setting page. It's working for early years and secondary (no news yet for 14-25 and Early help). Please could you have a look? Thanks.

![image](https://cloud.githubusercontent.com/assets/10434416/6485769/e79f1fa6-c27d-11e4-9772-39becfb3f637.png)

**Comment by LidorLapid** [comment]
Resolved.
