### ISSUE TITLE
Footer on Kelsi

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#62]
Is there supposed to be a footer on Kelsi? Where do the site map and cookies policy live? Thanks.

**Comment by LidorLapid** [comment]
There is a footer on KELSI, but it's not meant to contain any links -- it's purely decorative. Site map exists but isn't being linked to from anywhere (I believe this is also the case for kent.gov). Cookies policy can currently be accessed via the link on the cookie law banner or through search.

Would you like more prominent links for these? They'd probably have to go just above or below the 'Contact us' link.

**Comment by CatherineIles** [comment]
Ok great. Charlotte’s created a page called ‘About this website’ which links to the Site map, cookies policy and privacy policy. How do we add this About this website page between Contact us and the logo? Is that something we can do?

Thanks

Cat

Catherine Iles | Digital Services | Kent County Council | External: 03000 416292 | Internal: 416292 | www.kent.gov.uk<http://www.kent.gov.uk/> | @kent_cc<http://www.twitter.com/kent_cc>

**Comment by LidorLapid** [comment]
I've added a link to 'About the website' between 'Contact us' and the logo. That part of the site isn't currently editable (although it can be made so if need be).

**Comment by CatherineIles** [comment]
Marvellous, thanks! If it’s editable, people will try to put loads of things on that left hand panel so prob best if it’s not. Thanks!

Catherine Iles | Digital Services | Kent County Council | External: 03000 416292 | Internal: 416292 | www.kent.gov.uk<http://www.kent.gov.uk/> | @kent_cc<http://www.twitter.com/kent_cc>
