### ISSUE TITLE
News page promo

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/kelsi#63]
The promo/feature item on the News page behaves differently to the ones on the settings landing pages. Is it worth making them the same for consistency? 

News page promo - the whole thing is a link including the description. When clicked, everything is underlined dark blue (see screen grab below). There's no 'Read more'.

Settings page promo - the pic, headline and 'Read more' are links. The description isn't. 

![image](https://cloud.githubusercontent.com/assets/10434416/6662660/ecac61fc-cbb5-11e4-9826-5b2ce4305460.png)

**Comment by LidorLapid** [comment]
Done.
