### ISSUE TITLE
event metadata

### ISSUE THREAD

**Issue by charlottesales** [kentcc/kelsi#68]
is it possible to make the event metadata fields mandatory please.
so: 
- Venue
- Event address
- Cost
- How to apply

Also:
- is it possible to change the field "event address" to say "venue address" just so that it is consistent with the venue field. 
- can we change "how to apply" to say "how to book" as I think this fits better with events and then change the heading that pulls through to the page to reflect this. 

Thank you!

**Comment by LidorLapid** [comment]
All done.
