### ISSUE TITLE
E-bulletin - number of items allowed to appear each week

### ISSUE THREAD

**Issue by victoriafraser** [kentcc/kelsi#71]
The no of items to be included in the weekly e-bulletin needs to be increased to 15 to allow for exceptional weeks at the beginning and end of term when there are likely to be slightly more than 10 news articles. 

Just to check though that if there are fewer than 15 (say only 8) in quieter weeks that fewer articles can appear - ie you don't have to have 15 articles displaying all the time...........

**Comment by LidorLapid** [comment]
I can increase the number to 15, but this will mean that you will have to be diligent in unticking the 'Is in e-bulletin' metadata field and ensure that only those articles that you want to appear have that metadata field ticked. (Currently, you can leave them all ticked and only the latest 10 will be displayed.) I believe Allan will also have to make a small change to the MailChimp template to accommodate this. Please let me know if you'd like us to go ahead with this change.

**Comment by LidorLapid** [comment]
Done.
