### ISSUE TITLE
Text indentation

### ISSUE THREAD

**Issue by victoriafraser** [kentcc/kelsi#8]
![image](https://cloud.githubusercontent.com/assets/10435951/5722912/137d0b50-9b38-11e4-9dbb-84e5004b1946.png)

The indentation is different for the header text and body text as per above example

**Comment by charlottesales** [comment]
as part of this the bullets aren't indented either so this needs looking at too.

**Comment by LidorLapid** [comment]
Hi Charlotte. The bullet points indentation is a separate problem. Would you mind logging a new issue for it please?

**Comment by LidorLapid** [comment]
Thanks for logging this issue -- I've applied some styling changes to resolve it.
